# Generated by Django 5.0.4 on 2024-10-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_rename_number_contract_number_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='object',
            field=models.TextField(verbose_name='Objeto de Contrato'),
        ),
    ]
