# Generated by Django 5.0.4 on 2024-10-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ta',
            field=models.CharField(choices=[('1', 'TA 1'), ('2', 'TA 2'), ('3', 'TA 3'), ('4', 'TA 4')], default=1, max_length=200, verbose_name='TA'),
            preserve_default=False,
        ),
    ]
