# Generated by Django 5.0.4 on 2024-10-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract',
            new_name='number',
        ),
        migrations.AddField(
            model_name='contract',
            name='cnpj_cpf',
            field=models.CharField(default=1, max_length=200, verbose_name='CNPJ/CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='font',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero do Contrato'),
        ),
        migrations.AddField(
            model_name='contract',
            name='value_global',
            field=models.CharField(default=1, max_length=200, verbose_name='Numero do Contrato'),
            preserve_default=False,
        ),
    ]
