# Generated by Django 5.0.4 on 2024-10-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_value_mensal_alter_contract_value_global'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='number',
            new_name='number_contract',
        ),
        migrations.AddField(
            model_name='contract',
            name='number_process',
            field=models.CharField(default=1, max_length=200, verbose_name='Numero do Processo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='font',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fonte de Recurso'),
        ),
    ]
