# Generated by Django 5.0.4 on 2025-01-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_contract_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='ta',
            field=models.CharField(blank=True, choices=[('1', 'TA 1'), ('2', 'TA 2'), ('3', 'TA 3'), ('4', 'TA 4'), ('5', 'TA 5'), ('6', 'TA 6')], max_length=200, null=True, verbose_name='TA'),
        ),
    ]
